name: Auto Merge Pull Request

on:
  push:
    branches:
      - dev

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Check commit message
        id: check_commit_message
        run: |
          echo "::set-output name=commit_message::$(git log -1 --pretty=format:"%s")"
      
      - name: Create Pull Request
        if: contains(steps.check_commit_message.outputs.commit_message, '❗:')
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automated PR based on commit message"
          title: "Automated PR: ${{ github.event.head_commit.message }}"
          body: "Automated PR based on commit message pattern."
          base: main
          branch: "automerge-${{ github.run_id }}"
      
      - name: Enable Auto-Merge
        if: contains(steps.check_commit_message.outputs.commit_message, '❗:')
        uses: pascalgn/automerge-action@v0.14.3
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "automerge"
          MERGE_METHOD: "squash"
